"""outcome manual_price_bps

Revision ID: c09606c69fe5
Revises: c24eef58b62a
Create Date: 2026-06-25 07:26:12.059555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09606c69fe5'
down_revision: Union[str, None] = 'c24eef58b62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcomes', sa.Column('manual_price_bps', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcomes', 'manual_price_bps')
    # ### end Alembic commands ###
