"""initial schema

Revision ID: c24eef58b62a
Revises: 
Create Date: 2026-06-24 20:03:58.620741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c24eef58b62a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('EXTERNAL', 'HOUSE', 'USER', 'POOL', name='account_type'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_accounts_type'), 'ledger_accounts', ['type'], unique=False)
    op.create_table('ledger_tx',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'BET', 'PAYOUT', 'REFUND', 'CASHOUT', 'RAKE', 'ADJUST', name='tx_type'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_tx_type'), 'ledger_tx', ['type'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'RESOLVED', 'VOID', name='market_status'), nullable=False),
    sa.Column('rake_bps', sa.BigInteger(), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_outcome_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_status'), 'markets', ['status'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_id', sa.UUID(), nullable=False),
    sa.Column('from_account_id', sa.UUID(), nullable=False),
    sa.Column('to_account_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name='amount_positive'),
    sa.ForeignKeyConstraint(['from_account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['tx_id'], ['ledger_tx.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_from_account_id'), 'ledger_entries', ['from_account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_to_account_id'), 'ledger_entries', ['to_account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_tx_id'), 'ledger_entries', ['tx_id'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=280), nullable=False),
    sa.Column('pool_account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['pool_account_id'], ['ledger_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_market_id'), 'outcomes', ['market_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shadybank_account_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pan_enc', sa.String(length=512), nullable=False),
    sa.Column('ledger_account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['ledger_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_shadybank_account_id'), 'users', ['shadybank_account_id'], unique=True)
    op.create_table('bets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('outcome_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stake_cents', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('tx_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ),
    sa.ForeignKeyConstraint(['tx_id'], ['ledger_tx.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_bets_market_id'), 'bets', ['market_id'], unique=False)
    op.create_index(op.f('ix_bets_outcome_id'), 'bets', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_bets_user_id'), 'bets', ['user_id'], unique=False)
    op.create_table('cashouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='cashout_status'), nullable=False),
    sa.Column('tx_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tx_id'], ['ledger_tx.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashouts_status'), 'cashouts', ['status'], unique=False)
    op.create_index(op.f('ix_cashouts_user_id'), 'cashouts', ['user_id'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='deposit_status'), nullable=False),
    sa.Column('bank_description', sa.String(length=120), nullable=False),
    sa.Column('tx_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tx_id'], ['ledger_tx.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_deposits_status'), 'deposits', ['status'], unique=False)
    op.create_index(op.f('ix_deposits_user_id'), 'deposits', ['user_id'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('outcome_id', sa.UUID(), nullable=False),
    sa.Column('price_bps', sa.BigInteger(), nullable=False),
    sa.Column('pool_cents', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_snapshots_market_id'), 'odds_snapshots', ['market_id'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_outcome_id'), 'odds_snapshots', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_ts'), 'odds_snapshots', ['ts'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_token_enc', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_odds_snapshots_ts'), table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_outcome_id'), table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_market_id'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index(op.f('ix_deposits_user_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_status'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_index(op.f('ix_cashouts_user_id'), table_name='cashouts')
    op.drop_index(op.f('ix_cashouts_status'), table_name='cashouts')
    op.drop_table('cashouts')
    op.drop_index(op.f('ix_bets_user_id'), table_name='bets')
    op.drop_index(op.f('ix_bets_outcome_id'), table_name='bets')
    op.drop_index(op.f('ix_bets_market_id'), table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_users_shadybank_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_outcomes_market_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_ledger_entries_tx_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_to_account_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_from_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_markets_status'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_ledger_tx_type'), table_name='ledger_tx')
    op.drop_table('ledger_tx')
    op.drop_index(op.f('ix_ledger_accounts_type'), table_name='ledger_accounts')
    op.drop_table('ledger_accounts')
    # ### end Alembic commands ###
